version: '3'
services:
  node_backend:
    image: backend
    build: server
    ports:
      - '4000:4000'
  pg:
    image: 'postgres:13'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PASS}
  react_frontend:
    image: frontend
    build: client
    ports:
      - '3000:3000'
